=== jmurteira/Data_Integration_1819/factos.dtd
<!ELEMENT paises  ( pais+ )>
<!ELEMENT pais  ( cod_telef, cod_inter, capital, cid_mais_pop, hino, moeda, populacao, area, lista_idiomas)>
<!ELEMENT lista_idiomas  (idioma+)>
<!ELEMENT cod_telef  ( #PCDATA )>
<!ELEMENT cod_inter  ( #PCDATA )>
<!ELEMENT capital  ( #PCDATA )>
<!ELEMENT cid_mais_pop  ( #PCDATA )>
<!ELEMENT hino  ( #PCDATA )>
<!ELEMENT moeda  ( #PCDATA )>
<!ELEMENT populacao  ( #PCDATA )>
<!ELEMENT area  ( #PCDATA )>
<!ELEMENT idioma  ( #PCDATA )>

<!ATTLIST pais iso CDATA #REQUIRED>
<!ATTLIST paises xmlns:xsi CDATA #IMPLIED>
<!ATTLIST paises xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== jmurteira/Data_Integration_1819/factos.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE paises SYSTEM "factos.dtd">
<paises xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factos.xsd">
     <pais iso="ESP">
          <nome>Espanha</nome>
          <cod_telef>+34</cod_telef>
          <cod_inter>.es</cod_inter>
          <capital>Madrid</capital>
          <cid_mais_pop>Madrid</cid_mais_pop>
          <hino>Marcha Real</hino>
          <moeda>Euro</moeda>
          <populacao>teste</populacao>
          <area>teste</area>
     </pais>
     <pais iso="PRT">
          <cod_telef>+351</cod_telef>
          <cod_inter>.pt</cod_inter>
          <capital>Lisboa</capital>
          <cid_mais_pop>Lisboa</cid_mais_pop>
          <hino>A Portuguesa</hino>
          <moeda>Euro</moeda>
          <populacao>Ovar</populacao>
          <area>92 090</area>
          <lista_idiomas>
               <idioma>[Português, Mirandês]</idioma>
          </lista_idiomas>
     </pais>
     <pais iso="MEX">
          <cod_telef>+52</cod_telef>
          <cod_inter>.mx</cod_inter>
          <capital>Cidade do México</capital>
          <cid_mais_pop>Cidade</cid_mais_pop>
          <hino>Hino nacional do México</hino>
          <moeda>Peso mexicano</moeda>
          <populacao>130 759 074</populacao>
          <area>1 964 380</area>
          <lista_idiomas>
               <idioma>[Espanhol]</idioma>
          </lista_idiomas>
     </pais>
     <pais iso="BRA">
          <cod_telef>+55</cod_telef>
          <cod_inter>.br</cod_inter>
          <capital>Brasília</capital>
          <cid_mais_pop>S</cid_mais_pop>
          <hino>Hino Nacional Brasileiro</hino>
          <moeda>Real</moeda>
          <populacao>210 867 954</populacao>
          <area>8 514 880</area>
          <lista_idiomas>
               <idioma>[Português]</idioma>
          </lista_idiomas>
     </pais>
     <pais iso="CYP">
          <cod_telef>+357</cod_telef>
          <cod_inter>.cy</cod_inter>
          <capital>Nicósia</capital>
          <cid_mais_pop>Nic</cid_mais_pop>
          <hino>Hino à Liberdade</hino>
          <moeda>Euro</moeda>
          <populacao>1 189 085</populacao>
          <area>9 251</area>
          <lista_idiomas>
               <idioma>[Grego, Turco, Inglês]</idioma>
          </lista_idiomas>
     </pais>
</paises>
